//! Generated canonical native surface records.

/// Number of authored `#[primitive]` declarations scanned by the surface
/// generator. Rich projection migration may lag this count, but source drift
/// must update the checked-in artifact deliberately.
pub const GENERATED_PRIMITIVE_DECLARATION_COUNT: usize = 93;

use crate::{NativeMemberKind, NativeReturnShape, NativeSurfaceRecord};
use phalcom_native_meta::*;

// Common static type expressions
pub static TYPE_INT: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Int);
pub static TYPE_FLOAT: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Float);
pub static TYPE_STRING: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::String);
pub static TYPE_BOOL: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Bool);
pub static TYPE_NIL: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Nil);
pub static TYPE_UNIT: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Unit);
pub static TYPE_OBJECT: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Object);
pub static TYPE_NUMBER: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Number);
pub static TYPE_CLASS: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Class);
pub static TYPE_BEHAVIOR: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Behavior);
pub static TYPE_MESSAGE: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Message);
pub static TYPE_LIST: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::List);
pub static TYPE_MAP: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Map);
pub static TYPE_SET: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Set);
pub static TYPE_BYTES: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Bytes);
pub static TYPE_ERROR: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Error);
pub static TYPE_FIBER: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Fiber);
pub static TYPE_RESOURCE: TypeExprSpec = TypeExprSpec::Universe(UniverseKey::Resource);
pub static TYPE_UNKNOWN: TypeExprSpec = TypeExprSpec::Unknown;

// Common parameter tuples
pub static PARAMS_EMPTY: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[],
    labeled: &[],
    rest: None,
};

pub static PARAMS_ONE_INT: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[TypeExprSpec::Universe(UniverseKey::Int)],
    labeled: &[],
    rest: None,
};

pub static PARAMS_ONE_FLOAT: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[TypeExprSpec::Universe(UniverseKey::Float)],
    labeled: &[],
    rest: None,
};

pub static PARAMS_ONE_STRING: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[TypeExprSpec::Universe(UniverseKey::String)],
    labeled: &[],
    rest: None,
};

pub static PARAMS_ONE_BOOL: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[TypeExprSpec::Universe(UniverseKey::Bool)],
    labeled: &[],
    rest: None,
};

pub static PARAMS_ONE_OBJECT: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[TypeExprSpec::Universe(UniverseKey::Object)],
    labeled: &[],
    rest: None,
};

pub static PARAMS_ONE_UNKNOWN: ParameterTupleSpec = ParameterTupleSpec {
    positional: &[TypeExprSpec::Unknown],
    labeled: &[],
    rest: None,
};

macro_rules! define_callable {
    ($name:ident, $params:ident, $ret:ident) => {
        pub static $name: CallableTypeSpec = CallableTypeSpec {
            type_params: &[],
            params: &$params,
            return_type: &$ret,
        };
    };
}

define_callable!(CALLABLE_GETTER_INT, PARAMS_EMPTY, TYPE_INT);
define_callable!(CALLABLE_GETTER_FLOAT, PARAMS_EMPTY, TYPE_FLOAT);
define_callable!(CALLABLE_GETTER_STRING, PARAMS_EMPTY, TYPE_STRING);
define_callable!(CALLABLE_GETTER_BOOL, PARAMS_EMPTY, TYPE_BOOL);
define_callable!(CALLABLE_GETTER_UNIT, PARAMS_EMPTY, TYPE_UNIT);
define_callable!(CALLABLE_GETTER_OBJECT, PARAMS_EMPTY, TYPE_OBJECT);
define_callable!(CALLABLE_GETTER_UNKNOWN, PARAMS_EMPTY, TYPE_UNKNOWN);

define_callable!(CALLABLE_BINARY_INT_INT, PARAMS_ONE_INT, TYPE_INT);
define_callable!(CALLABLE_BINARY_INT_BOOL, PARAMS_ONE_INT, TYPE_BOOL);
define_callable!(CALLABLE_BINARY_INT_FLOAT, PARAMS_ONE_INT, TYPE_FLOAT);
define_callable!(CALLABLE_BINARY_FLOAT_FLOAT, PARAMS_ONE_FLOAT, TYPE_FLOAT);
define_callable!(CALLABLE_BINARY_FLOAT_BOOL, PARAMS_ONE_FLOAT, TYPE_BOOL);
define_callable!(CALLABLE_BINARY_STRING_STRING, PARAMS_ONE_STRING, TYPE_STRING);
define_callable!(CALLABLE_BINARY_STRING_BOOL, PARAMS_ONE_STRING, TYPE_BOOL);
define_callable!(CALLABLE_BINARY_STRING_INT, PARAMS_ONE_INT, TYPE_STRING);
define_callable!(CALLABLE_BINARY_BOOL_BOOL, PARAMS_ONE_BOOL, TYPE_BOOL);
define_callable!(CALLABLE_BINARY_OBJ_BOOL, PARAMS_ONE_OBJECT, TYPE_BOOL);
define_callable!(CALLABLE_BINARY_OBJ_OBJ, PARAMS_ONE_OBJECT, TYPE_OBJECT);
define_callable!(CALLABLE_BINARY_OBJ_UNIT, PARAMS_ONE_OBJECT, TYPE_UNIT);

macro_rules! surface_record {
    (
        owner = $owner:ident,
        side = $side:ident,
        selector = $selector:literal,
        kind = $kind:ident,
        visibility = $vis:ident,
        callable = $callable:ident,
        params = $params:ident,
        returns = $returns:ident,
        effects = $effects:expr,
        raises = $raises:expr,
        flow = $flow:expr,
        intrinsic = $intrinsic:expr,
        return_shape = $shape:expr,
        docs = $docs:expr
    ) => {
        NativeSurfaceRecord {
            surface: PrimitiveSurfaceSpec {
                key: PrimitiveKey {
                    owner: UniverseKey::$owner,
                    side: NativeDispatch::$side,
                    selector: $selector,
                },
                visibility: NativeVisibility::$vis,
                stability: NativeStability::Stable,
                params: &$params,
                returns: &$returns,
                callable: &$callable,
                raises: $raises,
                effects: $effects,
                flow: $flow,
                since: None,
                deprecated_since: None,
                replacement: None,
                lifecycle: NativeLifecycleSpec::UNKNOWN,
                intrinsic: $intrinsic,
                trust: NativeTrust::Ordinary,
                docs: $docs,
                conceptual: None,
            },
            kind: NativeMemberKind::$kind,
            abi: PrimitiveAbi::Value,
            return_shape: $shape,
        }
    };
}

/// Canonical catalog of rich native surface records.
pub static NATIVE_SURFACES: &[NativeSurfaceRecord] = &[
    // --- Bool Surface ---
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "not",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_BOOL,
        params = PARAMS_EMPTY,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = Some(NativeIntrinsicId::BoolNot),
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Returns the logical negation of the receiver.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "and(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = Some(NativeIntrinsicId::BoolAnd),
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Computes logical conjunction with the given boolean operand.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "or(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = Some(NativeIntrinsicId::BoolOr),
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Computes logical disjunction with the given boolean operand.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "&(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Computes strict bitwise/logical AND.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "|(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Computes strict bitwise/logical OR.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "^(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Computes exclusive OR (XOR) with another boolean.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "==(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Returns true if both booleans have identical truth value.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "!=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_BOOL_BOOL,
        params = PARAMS_ONE_BOOL,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Returns true if both booleans have different truth values.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "ifTrue(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_OBJ_OBJ,
        params = PARAMS_ONE_OBJECT,
        returns = TYPE_OBJECT,
        effects = EffectSpec::Unknown,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Unknown,
        docs = Some("Executes block if receiver is true.")
    ),
    surface_record!(
        owner = Bool,
        side = Instance,
        selector = "ifFalse(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_OBJ_OBJ,
        params = PARAMS_ONE_OBJECT,
        returns = TYPE_OBJECT,
        effects = EffectSpec::Unknown,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Unknown,
        docs = Some("Executes block if receiver is false.")
    ),
    // --- Int Surface ---
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "+(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Adds integer other to receiver.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "-(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Subtracts integer other from receiver.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "*(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Multiplies integer receiver by other.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "//(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Truncating integer division.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "/(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_FLOAT,
        params = PARAMS_ONE_INT,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Floating point division of two integers.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "%(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Modulo remainder of integer division.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "**(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Exponentiation of receiver to integer power.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "<<(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Left bit-shift.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = ">>(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Arithmetic right bit-shift.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "&(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Bitwise AND.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "|(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Bitwise OR.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "^(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Bitwise XOR.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "~",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Bitwise NOT / complement.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "+",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Unary positive.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "-",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Unary negation.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "==(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_BOOL,
        params = PARAMS_ONE_INT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if two integers are equal.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "!=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_BOOL,
        params = PARAMS_ONE_INT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if two integers are not equal.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "<(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_BOOL,
        params = PARAMS_ONE_INT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is strictly less than other.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "<=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_BOOL,
        params = PARAMS_ONE_INT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is less than or equal to other.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = ">(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_BOOL,
        params = PARAMS_ONE_INT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is strictly greater than other.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = ">=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_BOOL,
        params = PARAMS_ONE_INT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is greater than or equal to other.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "toString",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_STRING,
        params = PARAMS_EMPTY,
        returns = TYPE_STRING,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("String"),
        docs = Some("Formats the integer as a decimal string.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "bitCount",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns the number of one bits in the two's-complement representation.")
    ),
    surface_record!(
        owner = Int,
        side = Instance,
        selector = "bitAt(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_INT_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns 1 or 0 at the specified bit index.")
    ),
    // --- Float Surface ---
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "+(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_FLOAT,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Adds float other to receiver.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "-(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_FLOAT,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Subtracts float other from receiver.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "*(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_FLOAT,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Multiplies float receiver by other.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "/(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_FLOAT,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Divides float receiver by other.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "**(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_FLOAT,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Raises float receiver to power.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "+",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_FLOAT,
        params = PARAMS_EMPTY,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Unary positive float.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "-",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_FLOAT,
        params = PARAMS_EMPTY,
        returns = TYPE_FLOAT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Float"),
        docs = Some("Unary negation of float.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "==(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_BOOL,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if two floating point values are equal.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "!=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_BOOL,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if two floating point values are not equal.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "<(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_BOOL,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is strictly less than other float.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "<=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_BOOL,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is less than or equal to other float.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = ">(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_BOOL,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is strictly greater than other float.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = ">=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_FLOAT_BOOL,
        params = PARAMS_ONE_FLOAT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Tests if receiver is greater than or equal to other float.")
    ),
    surface_record!(
        owner = Float,
        side = Instance,
        selector = "toString",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_STRING,
        params = PARAMS_EMPTY,
        returns = TYPE_STRING,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("String"),
        docs = Some("Formats float as decimal string.")
    ),
    // --- String Surface ---
    surface_record!(
        owner = String,
        side = Instance,
        selector = "+(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_STRING,
        params = PARAMS_ONE_STRING,
        returns = TYPE_STRING,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("String"),
        docs = Some("Concatenates string with another string.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "length",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns the character length of the string.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "size",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns the byte size of the string.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "at(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_INT,
        params = PARAMS_ONE_INT,
        returns = TYPE_STRING,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("String"),
        docs = Some("Returns single character substring at index.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "==(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_BOOL,
        params = PARAMS_ONE_STRING,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Compares string equality.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "!=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_BOOL,
        params = PARAMS_ONE_STRING,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Compares string inequality.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "<(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_BOOL,
        params = PARAMS_ONE_STRING,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Lexicographical comparison.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = "<=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_BOOL,
        params = PARAMS_ONE_STRING,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Lexicographical comparison.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = ">(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_BOOL,
        params = PARAMS_ONE_STRING,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Lexicographical comparison.")
    ),
    surface_record!(
        owner = String,
        side = Instance,
        selector = ">=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_STRING_BOOL,
        params = PARAMS_ONE_STRING,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Lexicographical comparison.")
    ),
    // --- Object Surface ---
    surface_record!(
        owner = Object,
        side = Instance,
        selector = "==(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_OBJ_BOOL,
        params = PARAMS_ONE_OBJECT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("General object equality.")
    ),
    surface_record!(
        owner = Object,
        side = Instance,
        selector = "!=(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_OBJ_BOOL,
        params = PARAMS_ONE_OBJECT,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("General object inequality.")
    ),
    surface_record!(
        owner = Object,
        side = Instance,
        selector = "toString",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_STRING,
        params = PARAMS_EMPTY,
        returns = TYPE_STRING,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("String"),
        docs = Some("Returns string representation of the object.")
    ),
    surface_record!(
        owner = Object,
        side = Instance,
        selector = "hash",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns hash integer for the object.")
    ),
    surface_record!(
        owner = Object,
        side = Instance,
        selector = "class",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_OBJECT,
        params = PARAMS_EMPTY,
        returns = TYPE_OBJECT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::ClassObject("Object"),
        docs = Some("Returns the class object of the receiver.")
    ),
    // --- List Surface ---
    surface_record!(
        owner = List,
        side = Instance,
        selector = "length",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns the number of elements in the list.")
    ),
    surface_record!(
        owner = List,
        side = Instance,
        selector = "size",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns the number of elements in the list.")
    ),
    surface_record!(
        owner = List,
        side = Instance,
        selector = "add(_)",
        kind = Method,
        visibility = Public,
        callable = CALLABLE_BINARY_OBJ_UNIT,
        params = PARAMS_ONE_OBJECT,
        returns = TYPE_UNIT,
        effects = EffectSpec::Known(&[NativeEffect::Mutation]),
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Receiver,
        intrinsic = None,
        return_shape = NativeReturnShape::Receiver,
        docs = Some("Appends an element to the list.")
    ),
    // --- Map Surface ---
    surface_record!(
        owner = Map,
        side = Instance,
        selector = "length",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns entry count in map.")
    ),
    surface_record!(
        owner = Map,
        side = Instance,
        selector = "size",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns entry count in map.")
    ),
    // --- Set Surface ---
    surface_record!(
        owner = Set,
        side = Instance,
        selector = "length",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns element count in set.")
    ),
    surface_record!(
        owner = Set,
        side = Instance,
        selector = "size",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_INT,
        params = PARAMS_EMPTY,
        returns = TYPE_INT,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Int"),
        docs = Some("Returns element count in set.")
    ),
    // --- Nil Surface ---
    surface_record!(
        owner = Nil,
        side = Instance,
        selector = "isNil",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_BOOL,
        params = PARAMS_EMPTY,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Always returns true for nil.")
    ),
    surface_record!(
        owner = Nil,
        side = Instance,
        selector = "notNil",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_BOOL,
        params = PARAMS_EMPTY,
        returns = TYPE_BOOL,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("Bool"),
        docs = Some("Always returns false for nil.")
    ),
    surface_record!(
        owner = Nil,
        side = Instance,
        selector = "toString",
        kind = Getter,
        visibility = Public,
        callable = CALLABLE_GETTER_STRING,
        params = PARAMS_EMPTY,
        returns = TYPE_STRING,
        effects = EffectSpec::Pure,
        raises = RaisesSpec::Unknown,
        flow = ReturnFlowSpec::Value,
        intrinsic = None,
        return_shape = NativeReturnShape::Instance("String"),
        docs = Some("Returns 'nil'.")
    ),
];
