//! Universe key definitions and binding catalog.

/// Schema version of the generated native surface manifest.
pub const NATIVE_SURFACE_SCHEMA_VERSION: u32 = 1;

/// Stable VM-free enumeration of every canonical built-in class.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Ord, PartialOrd)]
pub enum UniverseKey {
    Object,
    Behavior,
    Class,
    Metaclass,

    Number,
    Int,
    Float,
    String,
    Nil,
    Bool,
    True,
    False,
    Symbol,
    SelectorPattern,

    Function,
    Closure,
    BoundMethod,
    Method,
    MethodFamily,
    BoundMethodFamily,
    Family,

    Option,
    Some,
    None,
    Unit,

    Iterable,
    List,
    Map,
    Set,
    Tuple,
    Record,
    Range,
    Bytes,

    Module,
    Package,
    Project,
    System,
    Message,

    Error,
    MessageNotUnderstood,
    CannotYieldAcrossNativeFrame,
    UseAfterCloseError,

    Fiber,
    Resource,

    ProjectManifest,
    PackageInfo,
    PackageAuthor,
    PackageRequirement,
    ResolvedProjectDependency,
    ModuleDependency,
    ExportTable,
    Export,
    ExportKind,
    ChildModuleTable,
    ModuleIdentity,
    PackageIdentity,
    ProjectIdentity,
    Uri,
}

impl UniverseKey {
    pub const fn name(&self) -> &'static str {
        match self {
            Self::Object => "Object",
            Self::Behavior => "Behavior",
            Self::Class => "Class",
            Self::Metaclass => "Metaclass",
            Self::Number => "Number",
            Self::Int => "Int",
            Self::Float => "Float",
            Self::String => "String",
            Self::Nil => "Nil",
            Self::Bool => "Bool",
            Self::True => "True",
            Self::False => "False",
            Self::Symbol => "Symbol",
            Self::SelectorPattern => "SelectorPattern",
            Self::Function => "Function",
            Self::Closure => "Closure",
            Self::BoundMethod => "BoundMethod",
            Self::Method => "Method",
            Self::MethodFamily => "MethodFamily",
            Self::BoundMethodFamily => "BoundMethodFamily",
            Self::Family => "Family",
            Self::Option => "Option",
            Self::Some => "Some",
            Self::None => "None",
            Self::Unit => "Unit",
            Self::Iterable => "Iterable",
            Self::List => "List",
            Self::Map => "Map",
            Self::Set => "Set",
            Self::Tuple => "Tuple",
            Self::Record => "Record",
            Self::Range => "Range",
            Self::Bytes => "Bytes",
            Self::Module => "Module",
            Self::Package => "Package",
            Self::Project => "Project",
            Self::System => "System",
            Self::Message => "Message",
            Self::Error => "Error",
            Self::MessageNotUnderstood => "MessageNotUnderstood",
            Self::CannotYieldAcrossNativeFrame => "CannotYieldAcrossNativeFrame",
            Self::UseAfterCloseError => "UseAfterCloseError",
            Self::Fiber => "Fiber",
            Self::Resource => "Resource",
            Self::ProjectManifest => "ProjectManifest",
            Self::PackageInfo => "PackageInfo",
            Self::PackageAuthor => "PackageAuthor",
            Self::PackageRequirement => "PackageRequirement",
            Self::ResolvedProjectDependency => "ResolvedProjectDependency",
            Self::ModuleDependency => "ModuleDependency",
            Self::ExportTable => "ExportTable",
            Self::Export => "Export",
            Self::ExportKind => "ExportKind",
            Self::ChildModuleTable => "ChildModuleTable",
            Self::ModuleIdentity => "ModuleIdentity",
            Self::PackageIdentity => "PackageIdentity",
            Self::ProjectIdentity => "ProjectIdentity",
            Self::Uri => "Uri",
        }
    }

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "Object" => Some(Self::Object),
            "Behavior" => Some(Self::Behavior),
            "Class" => Some(Self::Class),
            "Metaclass" => Some(Self::Metaclass),
            "Number" => Some(Self::Number),
            "Int" => Some(Self::Int),
            "Float" => Some(Self::Float),
            "String" => Some(Self::String),
            "Nil" => Some(Self::Nil),
            "Bool" => Some(Self::Bool),
            "True" => Some(Self::True),
            "False" => Some(Self::False),
            "Symbol" => Some(Self::Symbol),
            "SelectorPattern" => Some(Self::SelectorPattern),
            "Function" => Some(Self::Function),
            "Closure" => Some(Self::Closure),
            "BoundMethod" => Some(Self::BoundMethod),
            "Method" => Some(Self::Method),
            "MethodFamily" => Some(Self::MethodFamily),
            "BoundMethodFamily" => Some(Self::BoundMethodFamily),
            "Family" => Some(Self::Family),
            "Option" => Some(Self::Option),
            "Some" => Some(Self::Some),
            "None" => Some(Self::None),
            "Unit" => Some(Self::Unit),
            "Iterable" => Some(Self::Iterable),
            "List" => Some(Self::List),
            "Map" => Some(Self::Map),
            "Set" => Some(Self::Set),
            "Tuple" => Some(Self::Tuple),
            "Record" => Some(Self::Record),
            "Range" => Some(Self::Range),
            "Bytes" => Some(Self::Bytes),
            "Module" => Some(Self::Module),
            "Package" => Some(Self::Package),
            "Project" => Some(Self::Project),
            "System" => Some(Self::System),
            "Message" => Some(Self::Message),
            "Error" => Some(Self::Error),
            "MessageNotUnderstood" => Some(Self::MessageNotUnderstood),
            "CannotYieldAcrossNativeFrame" => Some(Self::CannotYieldAcrossNativeFrame),
            "UseAfterCloseError" => Some(Self::UseAfterCloseError),
            "Fiber" => Some(Self::Fiber),
            "Resource" => Some(Self::Resource),
            "ProjectManifest" => Some(Self::ProjectManifest),
            "PackageInfo" => Some(Self::PackageInfo),
            "PackageAuthor" => Some(Self::PackageAuthor),
            "PackageRequirement" => Some(Self::PackageRequirement),
            "ResolvedProjectDependency" => Some(Self::ResolvedProjectDependency),
            "ModuleDependency" => Some(Self::ModuleDependency),
            "ExportTable" => Some(Self::ExportTable),
            "Export" => Some(Self::Export),
            "ExportKind" => Some(Self::ExportKind),
            "ChildModuleTable" => Some(Self::ChildModuleTable),
            "ModuleIdentity" => Some(Self::ModuleIdentity),
            "PackageIdentity" => Some(Self::PackageIdentity),
            "ProjectIdentity" => Some(Self::ProjectIdentity),
            "Uri" => Some(Self::Uri),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum UniverseBindingKind {
    Class,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub struct UniverseBindingSpec {
    pub key: UniverseKey,
    pub name: &'static str,
    pub kind: UniverseBindingKind,
    pub exported: bool,
    pub prelude: bool,
}

/// Canonical catalog of built-in universe bindings.
pub const UNIVERSE_BINDINGS: &[UniverseBindingSpec] = &[
    UniverseBindingSpec {
        key: UniverseKey::Object,
        name: "Object",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Behavior,
        name: "Behavior",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Class,
        name: "Class",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Metaclass,
        name: "Metaclass",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Number,
        name: "Number",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Int,
        name: "Int",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Float,
        name: "Float",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::String,
        name: "String",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Nil,
        name: "Nil",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Bool,
        name: "Bool",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::True,
        name: "True",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::False,
        name: "False",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Symbol,
        name: "Symbol",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::SelectorPattern,
        name: "SelectorPattern",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Function,
        name: "Function",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Closure,
        name: "Closure",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::BoundMethod,
        name: "BoundMethod",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Method,
        name: "Method",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::MethodFamily,
        name: "MethodFamily",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::BoundMethodFamily,
        name: "BoundMethodFamily",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Family,
        name: "Family",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Option,
        name: "Option",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Some,
        name: "Some",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::None,
        name: "None",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Unit,
        name: "Unit",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Iterable,
        name: "Iterable",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::List,
        name: "List",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Map,
        name: "Map",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Set,
        name: "Set",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Tuple,
        name: "Tuple",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Record,
        name: "Record",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Range,
        name: "Range",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Bytes,
        name: "Bytes",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Module,
        name: "Module",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Package,
        name: "Package",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Project,
        name: "Project",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::System,
        name: "System",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Message,
        name: "Message",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Error,
        name: "Error",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::MessageNotUnderstood,
        name: "MessageNotUnderstood",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::CannotYieldAcrossNativeFrame,
        name: "CannotYieldAcrossNativeFrame",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::UseAfterCloseError,
        name: "UseAfterCloseError",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Fiber,
        name: "Fiber",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: true,
    },
    UniverseBindingSpec {
        key: UniverseKey::Resource,
        name: "Resource",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ProjectManifest,
        name: "ProjectManifest",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::PackageInfo,
        name: "PackageInfo",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::PackageAuthor,
        name: "PackageAuthor",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::PackageRequirement,
        name: "PackageRequirement",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ResolvedProjectDependency,
        name: "ResolvedProjectDependency",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ModuleDependency,
        name: "ModuleDependency",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ExportTable,
        name: "ExportTable",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Export,
        name: "Export",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ExportKind,
        name: "ExportKind",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ChildModuleTable,
        name: "ChildModuleTable",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ModuleIdentity,
        name: "ModuleIdentity",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::PackageIdentity,
        name: "PackageIdentity",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::ProjectIdentity,
        name: "ProjectIdentity",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
    UniverseBindingSpec {
        key: UniverseKey::Uri,
        name: "Uri",
        kind: UniverseBindingKind::Class,
        exported: true,
        prelude: false,
    },
];
