const pending = Future.new()
const other = Future.new()
const f = Fiber.new || {
  System.print(pending.await)
  System.print("passed first await")
  System.print(other.await)
  System.print("passed second await")
  Fiber.yield("later yield")
  System.print("continued again")
}
System.print(f.call())
System.print(f.try("manual"))
System.print(pending.isReady)
pending.settleValue("too late")
System.runScheduled()
System.print(other.isReady)
other.settleValue("also too late")
System.runScheduled()
System.print(f.isDone)
const q = Future.new()
const scheduled = Fiber.new || { System.print(q.await); "scheduled terminal" }
scheduled.call()
System.schedule(scheduled)
System.runScheduled()
System.print(q.isReady)
System.print(scheduled.isDone)
q.settleValue(3)
System.runScheduled()
const r = Future.new()
const called = Fiber.new || { System.print(r.await); 7 }
called.try()
System.print(called.call(99))
System.print(r.isReady)
r.settleValue(4)
System.runScheduled()
