[package]
name = "phalcom-modules"
version = "0.1.0"
edition = "2024"

[dependencies]
phalcom-ast = { path = "../phalcom-ast" }
phalcom-common = { path = "../phalcom-common" }
thiserror = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = "3.17"
