import "./typing/type" as TypeModule
import "./typing/type_descriptor" as DescriptorModule
import "./typing/variance" as VarianceModule
import "./typing/type_parameter" as ParameterModule
import "./typing/generic_signature" as SignatureModule
import "./typing/type_environment" as EnvironmentModule
import "./typing/type_constructor" as ConstructorModule
import "./typing/applied_type" as AppliedModule
import "./typing/applied_member" as MemberModule
import "./typing/type_runtime" as RuntimeModule
import "./typing/errors" as ErrorModule

const Type = TypeModule.Type
const TypeDescriptor = DescriptorModule.TypeDescriptor
const Variance = VarianceModule.Variance
const TypeParameter = ParameterModule.TypeParameter
const TypeParameterOwner = SignatureModule.TypeParameterOwner
const GenericSignature = SignatureModule.GenericSignature
const TypeEnvironment = EnvironmentModule.TypeEnvironment
const TypeBinding = EnvironmentModule.TypeBinding
const TypeConstructor = ConstructorModule.TypeConstructor
const AppliedType = AppliedModule.AppliedType
const AppliedParameter = MemberModule.AppliedParameter
const AppliedMethod = MemberModule.AppliedMethod
const AppliedField = MemberModule.AppliedField
const TypeRuntime = RuntimeModule.TypeRuntime

const TypeError = ErrorModule.TypeError
const TypeDeclarationError = ErrorModule.TypeDeclarationError
const TypeApplicationError = ErrorModule.TypeApplicationError
const TypeArgumentCountError = ErrorModule.TypeArgumentCountError
const TypeBoundError = ErrorModule.TypeBoundError
const TypeConstraintError = ErrorModule.TypeConstraintError
const TypeParameterOwnerError = ErrorModule.TypeParameterOwnerError
const TypeEnvironmentConflictError = ErrorModule.TypeEnvironmentConflictError
const ReservedTypeSelectorError = ErrorModule.ReservedTypeSelectorError
const UnspecializedTypeError = ErrorModule.UnspecializedTypeError
