[package]
name = "phalcom-native-macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macro #[phalcom::primitive] for native Phalcom primitives."

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
phalcom-type-syntax = { path = "../phalcom-type-syntax" }
phalcom-native-meta = { path = "../phalcom-native-meta" }
phalcom-common = { path = "../phalcom-common" }

[dev-dependencies]
