[package]
name = "phalcom-repl"
version = "0.1.0"
edition = "2024"
autotests = false

[[bin]]
name = "phalcom-repl"
path = "src/main.rs"
test = false

[dependencies]
unicode-segmentation = "1.12.0"
reedline = "0.41.0"
nu-ansi-term = "0.50.1"
phalcom-core = { path = "../phalcom-core" }
phalcom-ast = { path = "../phalcom-ast" }
phalcom-lsp = { path = "../phalcom-lsp" }

[[test]]
name = "repl_phase_b"
path = "tests/repl_phase_b.rs"
