[package]
name = "phalcom-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = "0.22.2"
phalcom-ast = { path = "../phalcom-ast" }
phalcom-vm = { path = "../phalcom-vm" }
phalcom-common = { path = "../phalcom-common" }
thiserror = "1.0"