[package]
name = "phalcom-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
lalrpop-util = "0.22.2"
anyhow = "1.0.98"
logos = "0.15.0"
pretty_assertions = "1.4.1"
thiserror = "2.0.12"

[build-dependencies]
lalrpop = "0.22.2"