[package]
name = "phalcom-semantic"
version = "0.1.0"
edition = "2024"

[dependencies]
phalcom-ast = { path = "../phalcom-ast" }
phalcom-common = { path = "../phalcom-common" }
phalcom-modules = { path = "../phalcom-modules" }
phalcom-native-meta = { path = "../phalcom-native-meta" }
phalcom-type-meta = { path = "../phalcom-type-meta" }
thiserror = { workspace = true }
serde = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
tempfile = "3.17"
