[package]
name = "phalcom-syntax"
version = "0.1.0"
edition = "2024"

[dependencies]
phalcom-common = { path = "../phalcom-common" }
phalcom-vm = { path = "../phalcom-vm" }
lalrpop-util = "0.22.2"
regex = "1.10"

[build-dependencies]
lalrpop = "0.22.2"