[package]
name = "phalcom-test-support"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
tempfile = "3"

[dev-dependencies]
phalcom-ast = { path = "../phalcom-ast" }
phalcom-common = { path = "../phalcom-common" }
phalcom-core = { path = "../phalcom-core" }
phalcom-modules = { path = "../phalcom-modules" }
phalcom-semantic = { path = "../phalcom-semantic" }

[[test]]
name = "either"
path = "tests/either/mod.rs"
